apiVersion: 1

datasources:
  - name: PostgreSQL-Sink
    uid: postgresql-sink
    type: postgres
    url: postgres-sink:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: earthquakes_sink
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true